global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['web:5000']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']

